### ISSUE TITLE
Support for color themes

### ISSUE THREAD

**Issue by ryanmusante** [acaloiaro/di-tui#13]
Is there a way to change the color theme within config.yml for the interface?

**Comment by acaloiaro** [comment]
Not currently. I'd be happy to entertain the idea.

Feel free to share what you think would be a reasonable amount of configuration in `config.yml`. 

If I recall correctly, I used a single hard-coded color across the whole app, defaulting to your terminal colors for all other text.

That would mean something like this in `config.yml`

```yaml
primary_color: #HEXCODE
secondary_color: #HEXCODE
```

**Comment by ryanmusante** [comment]
Yes, if I could change foreground t st and background color, that would be fantastic. I want to match my grubhub-dark theme with kitty term.

**Comment by acaloiaro** [comment]
Do you mind sharing what it looks like in kitty right now? 

It's been a while since I've worked on the _views_ for this application. I believe it was somewhere around 2018 when I implemented all that, so I'll need to refresh myself. 

With that said, I'm fairly confident I'm only changing text colors, and not the background. So, I believe your terminal background color is what you'll see. So I'd love to see an image of your terminal running `di-tui`, and perhaps a screenshot of it _not_ running `di-tui`, with something innocuous on the screen.

**Comment by ryanmusante** [comment]
So, when I switch manually to the darker config through the kitten, I can get closer to what I want, but I would like the ability to modify separate from it.
```
kitty +kitten themes    
```

di-tui screeen interface
![di-tui](https://github.com/acaloiaro/di-tui/assets/26808646/2e8f6363-d981-4a87-9cc0-7dea7efb1329)
kitty config interface
![kitty-config](https://github.com/acaloiaro/di-tui/assets/26808646/d39994b0-a4bb-4fa7-9162-e88bc94f038a)
terminal output 
![output](https://github.com/acaloiaro/di-tui/assets/26808646/cb887dfe-3c79-4403-94e1-488971dc12a5)

**Comment by acaloiaro** [comment]
Ok thanks a lot, that's interesting. `di-tui` is clearly setting a background, although perhaps not directly.

**Comment by acaloiaro** [comment]
I've got a themeable build ready, but I want to fiddle with the default colors some more before triggering a release.

**Comment by acaloiaro** [comment]
@ryanmusante If you're comfortable checking out a branch and running the app with `go run main.go`, you can try out the branch associated with this PR to see if you can achieve what you'd hoped to achieve style-wise.

Have a look at its `README.md` for a starter theme to start making your changes from.

**Comment by ryanmusante** [comment]
Sure, to confirm, the branch is?
git clone https://github.com/acaloiaro/di-tui/tree/add-color-theme-support

**Comment by acaloiaro** [comment]
Yep that's the one.

**Comment by ryanmusante** [comment]
I installed with go, but for some reason, it won't launch the binary

~ > ps -ef | grep di-tui
```
────────────────────────────────────────────────────────────────────────────────
     STDIN
 413 root        5703       2  0 10:44 ?        00:00:00 [kworker/u32:5-events_u
     nbound]
 414 root        5704       2  0 10:44 ?        00:00:00 [kworker/u32:6]
 415 ryan        5712    2174  0 10:45 pts/2    00:00:00 /home/ryan/go/bin/di-tu
```
~ > locate di-tui
```
/home/ryan/.config/di-tui
/home/ryan/.config/di-tui/config.yml
/home/ryan/go/bin/di-tui
/home/ryan/go/pkg/mod/cache/download/github.com/acaloiaro/di-tui
/home/ryan/go/pkg/mod/cache/download/github.com/acaloiaro/di-tui/@v
/home/ryan/go/pkg/mod/cache/download/github.com/acaloiaro/di-tui/@v/list
/home/ryan/go/pkg/mod/cache/download/github.com/acaloiaro/di-tui/@v/v1.3.15.info
/home/ryan/go/pkg/mod/cache/download/github.com/acaloiaro/di-tui/@v/v1.3.15.lock
/home/ryan/go/pkg/mod/cache/download/github.com/acaloiaro/di-tui/@v/v1.3.15.mod
/home/ryan/go/pkg/mod/cache/download/github.com/acaloiaro/di-tui/@v/v1.3.15.zip
/home/ryan/go/pkg/mod/cache/download/github.com/acaloiaro/di-tui/@v/v1.3.15.ziphash
/home/ryan/go/pkg/mod/cache/download/sumdb/sum.golang.org/lookup/github.com/acaloiaro/di-tui@v1.3.15
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/.github
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/.gitignore
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/.goreleaser.yml
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/CHANGELOG.md
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/LICENSE
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/README.md
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/app
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/components
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/config
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/context
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/difm
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/go.mod
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/go.sum
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/main.go
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/player
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/views
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/.github/workflows
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/.github/workflows/goreleaser.yml
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/app/app.go
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/components/components.go
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/config/config.go
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/context/context.go
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/difm/difm.go
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/player/player.go
/home/ryan/go/pkg/mod/github.com/acaloiaro/di-tui@v1.3.15/views/views.go
```

**Comment by acaloiaro** [comment]
Unfortunately this isn't related to the theme branch. Believe it or not, di.fm is suffering an outage https://maintenance-di.pages.dev/

In the mean time, you can `go install github.com/acaloiaro/di-tui@add-color-theme-support` to get this proposed theme build installed locally. 

Once di.fm is back online and I get your test results back, I can cut a build assuming there are no issues.

**Comment by ryanmusante** [comment]
Digitally Imported has been a life giving apparatus to be honest. Electronia in rare form. There is no other streaming service that even compares. Thanks to all your work with this app!

**Comment by acaloiaro** [comment]
np! This multi-day di.fm outage is painful.

**Comment by ryanmusante** [comment]
Is it another DDOS? What purpose do hackers have in breaking up a music service? That's dumb

**Comment by acaloiaro** [comment]
Their data center suffered a fire, resulting in a power outage.

**Comment by acaloiaro** [comment]
DI is back in biz: `go install github.com/acaloiaro/di-tui@add-color-theme-support` and give it a whirl

**Comment by acaloiaro** [comment]
Fixed by #14

**Comment by ryanmusante** [comment]
Looks great with default!

![Screenshot from 2023-07-22 12-40-53](https://github.com/acaloiaro/di-tui/assets/26808646/58e35c81-bd7e-424a-9e30-8d44102169f0)

**Comment by acaloiaro** [comment]
Awesome, thanks for testing and requesting!
