### ISSUE TITLE
Feature Request spectrum analyzer embedded

### ISSUE THREAD

**Issue by ryanmusante** [acaloiaro/di-tui#19]
Is an ASCII spectrum analyzer embedded into window something you might consider adding?

![image](https://github.com/acaloiaro/di-tui/assets/26808646/12b6dd64-81d0-4b12-b226-da96c7913ca1)
https://github.com/r4d10n/retrogram-rtlsdr

**Comment by acaloiaro** [comment]
I’m not at all opposed to adding it. It’s something that I’ve always considered a nice thing to have. However, I don’t want to do the work to add it. Are you interested in opening a PR?

**Comment by ryanmusante** [comment]
Sure, I can help out

**Comment by ryanmusante** [comment]
No time at the moment but will reopen
