### ISSUE TITLE
A simpler way to download the album art

### ISSUE THREAD

**Issue by moniquelive** [acaloiaro/di-tui#22]
Would you be interested in a PR for a [simpler way](https://github.com/acaloiaro/di-tui/blob/7df5f3391de100198ed0c4305fff36fe89a2cd7b/app/app.go#L25) of downloading the album cover art?

**Comment by acaloiaro** [comment]
Sure. Not a lot of thought went into that code, so if it can be improved I welcome the contribution!

> Would you be interested in a PR for a [simpler way](https://github.com/acaloiaro/di-tui/blob/7df5f3391de100198ed0c4305fff36fe89a2cd7b/app/app.go#L25) of downloading the album cover art?
